#!/usr/bin/env bash


# Get the current production server and
# set TARGET to the other server
CURRENT=$(curl -s http://161.35.252.207:3001/hostname)
if [ "$CURRENT" = "blue-production" ]; then
  TARGET="165.22.2.7"
  echo "Promoting stage env to prod at ip address " $TARGET " on port 3001"
  doctl compute floating-ip-action assign 161.35.252.207 217997548 --context jenkins
elif [ "$CURRENT" = "green-production" ]; then
  TARGET="142.93.193.167"
  echo "Promoting stage env to prod at ip address " $TARGET " on port 3001"
  doctl compute floating-ip-action assign 161.35.252.207 218158847 --context jenkins
else
  echo "Something is not right! 😬"
  exit -1
fi

CURRENT=$(curl -s http://161.35.252.207:3001/hostname)
echo "Current deployment is now" $CURRENT "on port 3001"
