#!/usr/bin/env bash

# Get the current production server and
# set TARGET to the other server
doctal auth init --access-token "7743031e82923852c7a305f9de2ccd72bca99d7e686381033d3cf4f638cf87ff"
CURRENT=$(curl -s http://161.35.252.207:3001/hostname)
if [ "$CURRENT" = "blue-production" ]; then
  TARGET="165.22.2.7"
  echo "Promoting stage env to prod at ip address " $TARGET " on port 3001"
  doctl compute floating-ip-action assign 161.35.252.207 217997548
elif [ "$CURRENT" = "green-production" ]; then
  TARGET="142.93.193.167"
  echo "Promoting stage env to prod at ip address " $TARGET " on port 3001"
  doctl compute floating-ip-action assign 161.35.252.207 218158847
else
  echo "Something is not right! 😬"
  exit -1
fi

CURRENT=$(curl -s http://161.35.252.207:3001/hostname)
echo "Current deployment is now" $CURRENT "on port 3001"
